name: battery_alert
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Widgets
  cupertino_icons: ^1.0.2 # Provides iOS-style icons.
  flutter_svg: ^2.0.9 # Renders SVG files as Flutter widgets.
  dotted_border: ^2.1.0 # Creates dotted borders around widgets.
  simple_ripple_animation: ^0.0.8 # Simple ripple effect for widgets.
  awesome_ripple_animation: ^2.0.0 # More customizable ripple effect.
  flutter_rating_bar: ^4.0.1 # Star rating widget.
  flutter_sticky_header: ^0.6.5 # Sticky headers for scrolling lists.
  lite_rolling_switch: ^1.0.1 # Rolling switch widget.
  # flutter_switch: ^0.3.2 # Simple toggle switch widget.
  liquid_progress_indicator_v2: ^0.5.0 # Liquid-like progress indicator.
  carousel_slider: ^4.2.1 # Carousel slider for images or widgets.
  dots_indicator: ^3.0.0 # Page indicator dots for carousels or pagers.
  expand_widget: ^3.1.1 # Expandable content widget.
  percent_indicator: ^4.2.3 # Circular or linear progress indicators.

  # Data Handling
  get: ^4.6.6 # State management solution.
  # get: ^5.0.0-release-candidate-5 # State management solution.
  intl: ^0.18.1 # Internationalization and localization.
  shared_preferences: ^2.2.2 # Persistent key-value storage.
  dartz: ^0.10.1 # Functional programming utilities for error handling.

  # Notifications
  fluttertoast: ^8.2.4 # Toast-style notifications.
  flutter_local_notifications: ^16.3.0 # Scheduling local notifications.

  # Firebase
  firebase_auth: ^4.15.3 # Firebase authentication services.
  firebase_core: ^2.24.2 # Core Firebase functionality for Flutter apps.

  # Device Info
  device_apps: ^2.2.0 #* Accessing installed apps icons on the device.
  # installed_apps: ^1.4.0 #* use this instead of device apps
  battery_info: ^1.1.1 # Battery information.
  battery_plus: ^5.0.2 # More comprehensive battery information.
  # device_info_plus: ^9.1.1 # Device information like model, OS, etc.
  file_selector: ^1.0.2 # manages files and interactions with file dialogs.
  share_plus: ^7.2.1 # share content from your Flutter app via the platform's share dialog.
  image_preview: ^1.0.5 # Preview pictures and support left and right sliding switch.
  image_picker: ^1.0.7
  open_store: ^0.5.0 #open playstore
  url_launcher: ^6.2.4 #

  # Audio
  audio_service: ^0.18.12
  audioplayers: ^5.2.1
  just_audio: ^0.9.36

  # Background Services
  flutter_background_service: ^5.0.5 # Running background tasks.
  flutter_background_service_android: ^6.2.2 # Android-specific background service functions.

  # Other
  flutter_screenutil: ^5.9.0 # Responsive screen adaptation.
  app_usage: ^3.0.1 # Accessing app usage information.
  flutter_datetime_picker_plus: ^2.1.0
  timezone: ^0.9.2
  rating_dialog: ^2.0.4
  in_app_review: ^2.0.8 #
  file_picker: ^6.1.1
  flutter_overlay_window: ^0.4.3

  #...
  flutter_foreground_task: ^6.1.2
  #google payment
  in_app_purchase: ^3.1.13
  onepref: ^0.0.16
  app_to_foreground: ^0.0.3
  flutter_localizations:
    sdk: flutter
  torch_light: ^1.0.0
  torch_controller: ^2.0.1
  vibration: ^1.8.4
  assets_audio_player: ^3.1.1
  # flutter_sizer: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Flutter Launcher Icons for managing app icons
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logos/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logos/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logos/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/logos/
    - assets/svgs/
    - assets/gifs/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-Regular.ttf
